export const WIKIMATCH_GROUNDING_MAX_OPTION_BUDGET = 50;
export const WIKIMATCH_SURFACE_PROTECTION_PERCENTILE = 0.1;
export const WIKILINK_EVIDENCE_DISTANCE = 700;
export const WIKILINK_WINDOW_LENGTH = 1800;
